#!/usr/bin/env bash
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

PGHOST="${PGHOST:-${MIR2_DB_HOST:-127.0.0.1}}"
PGPORT="${PGPORT:-${MIR2_DB_PORT:-5432}}"
PGUSER="${PGUSER:-${MIR2_DB_USER:-mir2}}"
PGPASSWORD="${PGPASSWORD:-${MIR2_DB_PASSWORD:-mir2_password}}"
PGDATABASE="${PGDATABASE:-${MIR2_DB_NAME:-mir2_game}}"

BATCH_ID="account-kv-migration-$(date +%Y%m%d_%H%M%S)"
DO_CLEANUP=false
DRY_RUN=false
REPORT_FILE=""

usage() {
  cat <<'EOF'
Usage: scripts/migrate_account_kv_to_accounts.sh [options]

Options:
  --batch-id <id>       Migration batch id (default: generated by timestamp)
  --cleanup-kv          Delete migrated account keys from kv_store after success
  --dry-run             Parse and verify only, do not write accounts table
  --report-file <path>  Output reconciliation report path
  -h, --help            Show this help
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --batch-id)
      BATCH_ID="$2"
      shift 2
      ;;
    --cleanup-kv)
      DO_CLEANUP=true
      shift
      ;;
    --dry-run)
      DRY_RUN=true
      shift
      ;;
    --report-file)
      REPORT_FILE="$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage
      exit 1
      ;;
  esac
done

if [[ -z "${REPORT_FILE}" ]]; then
  REPORT_FILE="${PROJECT_ROOT}/logs/account_migration_${BATCH_ID}.report.txt"
fi
mkdir -p "$(dirname "${REPORT_FILE}")"

if ! command -v psql >/dev/null 2>&1; then
  echo "psql is required" >&2
  exit 1
fi
if ! command -v jq >/dev/null 2>&1; then
  echo "jq is required" >&2
  exit 1
fi
if ! command -v base64 >/dev/null 2>&1; then
  echo "base64 is required" >&2
  exit 1
fi

psql_cmd() {
  PGPASSWORD="${PGPASSWORD}" \
    psql -h "${PGHOST}" -p "${PGPORT}" -U "${PGUSER}" -d "${PGDATABASE}" \
      -v ON_ERROR_STOP=1 "$@"
}

record_row() {
  local username="$1"
  local account_id="$2"
  local status="$3"
  local error_message="$4"
  psql_cmd \
    -v batch_id="${BATCH_ID}" \
    -v username="${username}" \
    -v account_id="${account_id}" \
    -v status="${status}" \
    -v error_message="${error_message}" \
    -c "INSERT INTO account_kv_migration_rows
          (batch_id, username, account_id, status, error_message)
        VALUES
          (:'batch_id', :'username', NULLIF(:'account_id', '')::BIGINT, :'status', :'error_message')
        ON CONFLICT (batch_id, username) DO UPDATE SET
          account_id = EXCLUDED.account_id,
          status = EXCLUDED.status,
          error_message = EXCLUDED.error_message,
          migrated_at = NOW();" >/dev/null
}

upsert_account() {
  local account_id="$1"
  local username="$2"
  local password_hash="$3"
  local email="$4"
  local created_at="$5"
  local last_login="$6"
  local banned="$7"

  if [[ -n "${account_id}" && "${account_id}" != "0" ]]; then
    psql_cmd \
      -v account_id="${account_id}" \
      -v username="${username}" \
      -v password_hash="${password_hash}" \
      -v email="${email}" \
      -v created_at="${created_at}" \
      -v last_login="${last_login}" \
      -v banned="${banned}" \
      -c "INSERT INTO accounts
            (id, username, password_hash, email, created_at, last_login, banned)
          VALUES
            (:account_id::BIGINT,
             :'username',
             :'password_hash',
             NULLIF(:'email', ''),
             CASE
               WHEN :created_at::BIGINT > 0
               THEN TO_TIMESTAMP(:created_at::DOUBLE PRECISION / 1000.0)
               ELSE NOW()
             END,
             CASE
               WHEN :last_login::BIGINT > 0
               THEN TO_TIMESTAMP(:last_login::DOUBLE PRECISION / 1000.0)
               ELSE NULL
             END,
             :banned::BOOLEAN)
          ON CONFLICT (username) DO UPDATE SET
            id = EXCLUDED.id,
            password_hash = EXCLUDED.password_hash,
            email = EXCLUDED.email,
            last_login = EXCLUDED.last_login,
            banned = EXCLUDED.banned;" >/dev/null
  else
    psql_cmd \
      -v username="${username}" \
      -v password_hash="${password_hash}" \
      -v email="${email}" \
      -v created_at="${created_at}" \
      -v last_login="${last_login}" \
      -v banned="${banned}" \
      -c "INSERT INTO accounts
            (username, password_hash, email, created_at, last_login, banned)
          VALUES
            (:'username',
             :'password_hash',
             NULLIF(:'email', ''),
             CASE
               WHEN :created_at::BIGINT > 0
               THEN TO_TIMESTAMP(:created_at::DOUBLE PRECISION / 1000.0)
               ELSE NOW()
             END,
             CASE
               WHEN :last_login::BIGINT > 0
               THEN TO_TIMESTAMP(:last_login::DOUBLE PRECISION / 1000.0)
               ELSE NULL
             END,
             :banned::BOOLEAN)
          ON CONFLICT (username) DO UPDATE SET
            password_hash = EXCLUDED.password_hash,
            email = EXCLUDED.email,
            last_login = EXCLUDED.last_login,
            banned = EXCLUDED.banned;" >/dev/null
  fi
}

psql_cmd \
  -v batch_id="${BATCH_ID}" \
  -c "INSERT INTO account_kv_migration_batches (batch_id, status)
      VALUES (:'batch_id', 'running')
      ON CONFLICT (batch_id) DO UPDATE SET
        status = 'running',
        started_at = NOW(),
        completed_at = NULL,
        source_count = 0,
        migrated_count = 0,
        failed_count = 0,
        checksum = NULL;" >/dev/null

SOURCE_FILE="$(mktemp)"
trap 'rm -f "${SOURCE_FILE}"' EXIT

psql_cmd -At -F $'\t' \
  -c "SELECT key, encode(data, 'base64')
      FROM kv_store
      WHERE key LIKE 'account:username:%'
      ORDER BY key;" >"${SOURCE_FILE}"

SOURCE_COUNT=0
MIGRATED_COUNT=0
FAILED_COUNT=0

while IFS=$'\t' read -r key payload_b64; do
  [[ -z "${key}" ]] && continue
  SOURCE_COUNT=$((SOURCE_COUNT + 1))

  username="${key#account:username:}"
  if [[ -z "${username}" ]]; then
    FAILED_COUNT=$((FAILED_COUNT + 1))
    record_row "" "" "failed" "invalid storage key"
    continue
  fi

  if ! json_payload="$(printf '%s' "${payload_b64}" | base64 --decode 2>/dev/null)"; then
    FAILED_COUNT=$((FAILED_COUNT + 1))
    record_row "${username}" "" "failed" "base64 decode failure"
    continue
  fi

  if ! jq -e . >/dev/null 2>&1 <<<"${json_payload}"; then
    FAILED_COUNT=$((FAILED_COUNT + 1))
    record_row "${username}" "" "failed" "invalid json payload"
    continue
  fi

  account_id="$(jq -r '.id // 0' <<<"${json_payload}")"
  payload_username="$(jq -r '.username // ""' <<<"${json_payload}")"
  password_hash="$(jq -r '.password_hash // ""' <<<"${json_payload}")"
  email="$(jq -r '.email // ""' <<<"${json_payload}")"
  created_at="$(jq -r '.created_at // 0' <<<"${json_payload}")"
  last_login="$(jq -r '.last_login // 0' <<<"${json_payload}")"
  banned="$(jq -r '.banned // false' <<<"${json_payload}")"

  if [[ -n "${payload_username}" && "${payload_username}" != "${username}" ]]; then
    FAILED_COUNT=$((FAILED_COUNT + 1))
    record_row "${username}" "${account_id}" "failed" "payload username mismatch"
    continue
  fi

  if [[ -z "${password_hash}" ]]; then
    FAILED_COUNT=$((FAILED_COUNT + 1))
    record_row "${username}" "${account_id}" "failed" "empty password_hash"
    continue
  fi

  if [[ "${DRY_RUN}" == "true" ]]; then
    MIGRATED_COUNT=$((MIGRATED_COUNT + 1))
    record_row "${username}" "${account_id}" "skipped" "dry-run"
    continue
  fi

  if upsert_account "${account_id}" "${username}" "${password_hash}" "${email}" \
      "${created_at}" "${last_login}" "${banned}"; then
    MIGRATED_COUNT=$((MIGRATED_COUNT + 1))
    record_row "${username}" "${account_id}" "migrated" ""
  else
    FAILED_COUNT=$((FAILED_COUNT + 1))
    record_row "${username}" "${account_id}" "failed" "upsert failed"
  fi
done <"${SOURCE_FILE}"

CHECKSUM="$(sha256sum "${SOURCE_FILE}" | awk '{print $1}')"
BATCH_STATUS="completed"
if [[ "${DRY_RUN}" == "true" ]]; then
  BATCH_STATUS="dry_run"
elif [[ "${FAILED_COUNT}" -gt 0 ]]; then
  BATCH_STATUS="completed_with_failures"
fi

psql_cmd \
  -v batch_id="${BATCH_ID}" \
  -v status="${BATCH_STATUS}" \
  -v source_count="${SOURCE_COUNT}" \
  -v migrated_count="${MIGRATED_COUNT}" \
  -v failed_count="${FAILED_COUNT}" \
  -v checksum="${CHECKSUM}" \
  -c "UPDATE account_kv_migration_batches
      SET completed_at = NOW(),
          status = :'status',
          source_count = :source_count::BIGINT,
          migrated_count = :migrated_count::BIGINT,
          failed_count = :failed_count::BIGINT,
          checksum = :'checksum'
      WHERE batch_id = :'batch_id';" >/dev/null

if [[ "${DO_CLEANUP}" == "true" && "${DRY_RUN}" == "false" && "${FAILED_COUNT}" -eq 0 ]]; then
  psql_cmd \
    -v batch_id="${BATCH_ID}" \
    -c "DELETE FROM kv_store kv
        USING account_kv_migration_rows rows
        WHERE rows.batch_id = :'batch_id'
          AND rows.status = 'migrated'
          AND kv.key = 'account:username:' || rows.username;" >/dev/null
fi

{
  echo "batch_id=${BATCH_ID}"
  echo "status=${BATCH_STATUS}"
  echo "source_count=${SOURCE_COUNT}"
  echo "migrated_count=${MIGRATED_COUNT}"
  echo "failed_count=${FAILED_COUNT}"
  echo "dry_run=${DRY_RUN}"
  echo "cleanup_kv=${DO_CLEANUP}"
  echo "checksum=${CHECKSUM}"
  echo
  echo "[failed_rows]"
  psql_cmd -At -F $'\t' \
    -v batch_id="${BATCH_ID}" \
    -c "SELECT username, COALESCE(error_message, '')
        FROM account_kv_migration_rows
        WHERE batch_id = :'batch_id'
          AND status = 'failed'
        ORDER BY username;"
} >"${REPORT_FILE}"

echo "migration batch: ${BATCH_ID}"
echo "report: ${REPORT_FILE}"
